apiVersion: apps/v1
kind: Deployment
metadata:
  name: ast
  namespace: voip
  labels:
    component: asterisk
spec:
  replicas: 1
  selector:
    matchLabels:
      component: asterisk
  template:
    metadata:
      labels:
        component: asterisk
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      terminationGracePeriodSeconds: 2700
      volumes:
        - name: google-service-account
          secret:
            secretName: google-service-account
        - name: astdb
          emptyDir:
            medium: Memory
            sizeLimit: "1Gi"
        - name: logs
          emptyDir:
            medium: Memory
            sizeLimit: "1Gi"
        - name: sounds
          emptyDir: {}
        - name: spool
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      initContainers:
        - name: init
          image: ghcr.io/voxoco/asterisk:latest
          command: ["bash", "-c", "mkdir /var/log/asterisk/cel-custom /var/spool/asterisk/monitor /var/spool/asterisk/meetme /var/spool/asterisk/voicemail && cp -r /sounds/ /var/lib/asterisk/sounds"]
          volumeMounts:
            - name: logs
              mountPath: /var/log/asterisk
            - name: sounds
              mountPath: /var/lib/asterisk/sounds
            - name: spool
              mountPath: /var/spool/asterisk
      containers:
        - name: asterisk-sidecar
          image: ghcr.io/voxoco/asterisk-sidecar:latest
          ports:
            - containerPort: 4377
            - containerPort: 4573
          env:
            - name: TZ
              value: America/Chicago
            - name: KAMHOST
              value: kamailio-dmq
            - name: KAMSERVERID
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: serverId
            - name: NATSURL
              valueFrom:
                secretKeyRef:
                  name: nats-url
                  key: connectionString
            - name: MYSQL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          volumeMounts:
            - name: logs
              mountPath: /var/log/asterisk
            - name: sounds
              mountPath: /var/lib/asterisk/sounds
            - name: spool
              mountPath: /var/spool/asterisk
            - name: tmp
              mountPath: /tmp
            - name: google-service-account
              mountPath: /var/secrets/google
        - name: presence
          image: ghcr.io/voxoco/presence:latest
          ports:
            - name: http
              protocol: TCP
              containerPort: 9102
          env:
            - name: TZ
              value: America/Chicago
            - name: NATSURL
              valueFrom:
                secretKeyRef:
                  name: nats-url
                  key: connectionString
            - name: MYSQL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
        - name: asterisk
          image: ghcr.io/voxoco/asterisk:latest
          resources:
            requests:
              memory: 1Gi
              cpu: 2000m
            limits:
              memory: 2Gi
              cpu: 4000m
          ports:
            - containerPort: 5080
          lifecycle:
            preStop:
              exec:
                command: [ "/var/lib/asterisk/gracefulShutdown.sh" ]
          env:
            - name: TZ
              value: America/Chicago
            - name: MYSQL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
          volumeMounts:
            - name: astdb
              mountPath: /var/lib/asterisk/astdb
            - name: logs
              mountPath: /var/log/asterisk
            - name: sounds
              mountPath: /var/lib/asterisk/sounds
            - name: spool
              mountPath: /var/spool/asterisk
            - name: tmp
              mountPath: /tmp
      imagePullSecrets:
        - name: regcred

---

apiVersion: monitoring.gke.io/v1alpha1
kind: PodMonitor
metadata:
  name: asterisk
  namespace: voip
spec:
  selector:
    matchLabels:
      component: asterisk
  podMetricsEndpoints:
    - port: http
      path: /metrics
      scheme: http
      interval: 1m
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: "(asterisk_active_user_calls)"
          action: drop

---

apiVersion: autoscaling.gke.io/v1beta1
kind: MultidimPodAutoscaler
metadata:
  name: asterisk
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ast
  goals:
    metrics:
      - type: Resource
        resource:
          # Define the target CPU utilization request here
          name: cpu
          target:
            type: Utilization
            averageUtilization: 90
  constraints:
    global:
      minReplicas: 1
      maxReplicas: 5
    containerControlledResources: [ memory ]
    container:
      - name: '*'
        # Define boundaries for the memory request here
        requests:
          minAllowed:
            memory: 1Gi
          maxAllowed:
            memory: 2Gi
  policy:
    updateMode: Auto
