apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: kamailio-mcs
  namespace: voip
  labels:
    component: kamailio
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"8080":"webrtc-kamailio"}}'
spec:
  template:
    spec:
      selector:
        component: kamailio
      ports:
        - name: webrtc
          protocol: TCP
          port: 8080

---

apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: omnia-api-mcs
  namespace: voip
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"3031":"socket-api"}}'
spec:
  template:
    spec:
      selector:
        component: omnia-api
      ports:
        - name: rest
          protocol: TCP
          port: 3030
        - name: socket
          protocol: TCP
          port: 3031

---

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: webrtc-kamailio
  namespace: voip
spec:
  timeoutSec: 1800
  connectionDraining:
    drainingTimeoutSec: 1

---

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: socket-api
  namespace: voip
spec:
  healthCheck:
    port: 3030
    type: HTTP
    requestPath: /
  timeoutSec: 1800
  connectionDraining:
    drainingTimeoutSec: 2

---

apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: frontend-redirect
  namespace: voip
spec:
  redirectToHttps:
    enabled: true

---

apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: http-ingress
  namespace: voip
  annotations:
    networking.gke.io/static-ip: 34.117.222.234
    networking.gke.io/pre-shared-certs: "kube-api-voxo-co, api-voxo-co"
    networking.gke.io/frontend-config: frontend-redirect
spec:
  template:
    spec:
      backend:
        serviceName: omnia-api-mcs
        servicePort: 3030
      rules:
        - host: kube-api.voxo.co
          http:
            paths:
              - path: /
                backend:
                  serviceName: omnia-api-mcs
                  servicePort: 3030
              - path: /socket.io/
                backend:
                  serviceName: omnia-api-mcs
                  servicePort: 3031
              - path: /webrtc
                backend:
                  serviceName: kamailio-mcs
                  servicePort: 8080
