apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: innodb-cluster
  namespace: voip
spec:
  serviceName: "innodb-cluster"
  replicas: 2
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: innodb-cluster
  template:
    metadata:
      labels:
        app: innodb-cluster
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      volumes:
        - name: conf
          emptyDir: {}
      initContainers:
        - name: init
          image: ghcr.io/voxoco/innodb-cluster:latest
          command: ["bash", "/init.sh"]
          env:
            - name: TZ
              value: America/Chicago
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: clusterName
            - name: MYSQLSERVERID
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: serverId
          volumeMounts:
            - name: conf
              mountPath: /mnt/conf.d
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysqld-exporter
          image: prom/mysqld-exporter
          env:
            - name: DATA_SOURCE_NAME
              value: mysqld-exporter:123456@(127.0.0.1:3306)/
          ports:
            - name: metrics
              containerPort: 9104
          args:
            - --no-collect.info_schema.innodb_cmpmem
            - --no-collect.global_variables
            - --no-collect.info_schema.innodb_metrics
            - --no-collect.info_schema.query_response_time
        - name: sidecar
          image: ghcr.io/voxoco/innodb-cluster:latest
          command: ["bash", "/sidecar.sh"]
          env:
            - name: TZ
              value: America/Chicago
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: accessKey
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: secretAccessKey
            - name: CLUSTER_LEADER
              value: us-central1
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-pw
                  key: pw
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: clusterName
            - name: BACKUP_INTERVAL
              value: "43200"
          volumeMounts:
            - name: data
              mountPath: /mnt/data/mysql
        - name: mysql
          image: ghcr.io/voxoco/innodb-cluster:latest
          resources:
            requests:
              memory: 4Gi
              cpu: 800m
            limits:
              memory: 7Gi
              cpu: 3000m
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-pw
                  key: pw
            - name: MYSQL_ROOT_HOST
              value: '%'
            - name: TZ
              value: America/Chicago
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: conf
              mountPath: /etc/mysql
            - name: data
              mountPath: /var/lib/mysql
      imagePullSecrets:
        - name: regcred
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: premium-rwo
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: voip
  labels:
    app: innodb-cluster
spec:
  ports:
    - name: mysql
      port: 3306
  selector:
    app: innodb-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: innodb-cluster
  namespace: voip
spec:
  ports:
    - port: 3306
  selector:
    app: innodb-cluster
  clusterIP: None
---
apiVersion: monitoring.gke.io/v1alpha1
kind: PodMonitor
metadata:
  name: innodb-cluster
  namespace: voip
spec:
  selector:
    matchLabels:
      app: innodb-cluster
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 1m
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: "(mysql_global_status_connections|mysql_global_status_opened_files|mysql_global_status_queries|mysql_global_status_threads_connected|mysql_global_status_threads_running|mysql_global_status_uptime|mysql_slave_status_slave_io_running|mysql_slave_status_slave_sql_running|mysql_up)"
          action: keep
---
apiVersion: monitoring.gke.io/v1alpha1
kind: PodMonitor
metadata:
  name: innodb-cluster-commands
  namespace: voip
spec:
  selector:
    matchLabels:
      app: innodb-cluster
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 1m
      metricRelabelings:
        - sourceLabels: [command]
          regex: "(insert|delete|select|update)"
          action: keep
