apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnia-api
  namespace: voip
  labels:
    component: omnia-api
spec:
  replicas: 1
  selector:
    matchLabels:
      component: omnia-api
  template:
    metadata:
      labels:
        component: omnia-api
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      volumes:
        - name: google-service-account
          secret:
            secretName: google-service-account
      containers:
        - name: omnia-api
          image: ghcr.io/voxoco/omnia-api:latest
          resources:
            requests:
              memory: 300Mi
              cpu: 200m
            limits:
              memory: 600Mi
              cpu: 800m
          env:
            - name: TZ
              value: America/Chicago
            - name: NATSURL
              valueFrom:
                secretKeyRef:
                  name: nats-url
                  key: connectionString
            - name: MYSQL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
            - name: AUTHSECRET
              valueFrom:
                secretKeyRef:
                  name: api-auth-secret
                  key: authSecret
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: PORT
              value: "3030"
            - name: SOCKETPORT
              value: "3031"
            - name: NODE_ENV
              value: "production"
          volumeMounts:
            - name: google-service-account
              mountPath: /var/secrets/google
      imagePullSecrets:
        - name: regcred

---

apiVersion: autoscaling.gke.io/v1beta1
kind: MultidimPodAutoscaler
metadata:
  name: omnia-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: omnia-api
  goals:
    metrics:
      - type: Resource
        resource:
          # Define the target CPU utilization request here
          name: cpu
          target:
            type: Utilization
            averageUtilization: 90
  constraints:
    global:
      minReplicas: 1
      maxReplicas: 5
    containerControlledResources: [ memory ]
    container:
      - name: '*'
        # Define boundaries for the memory request here
        requests:
          minAllowed:
            memory: 300Mi
          maxAllowed:
            memory: 600Mi
  policy:
    updateMode: Auto
