apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rtpengine
  namespace: voip
  labels:
    component: rtpengine
spec:
  selector:
    matchLabels:
      component: rtpengine
  template:
    metadata:
      name: rtpengine
      labels:
        component: rtpengine
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: external
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 2700
      serviceAccountName: manager
      containers:
        - name: rtpengine
          image: ghcr.io/voxoco/rtpengine:latest
          ports:
            - containerPort: 22222
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "/gracefulShutdown.sh" ]
          env:
            - name: TZ
              value: America/Chicago
            - name: CLOUD
              value: gcp
        - name: rtpengine-sidecar
          image: ghcr.io/voxoco/rtpengine-sidecar:latest
          ports:
            - containerPort: 42187
          env:
            - name: TZ
              value: America/Chicago
            - name: KAMSERVERID
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: serverId
            - name: NATSURL
              valueFrom:
                secretKeyRef:
                  name: nats-url
                  key: connectionString
            - name: MYSQL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: rtpengine-metrics
  namespace: voip
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '22223'
spec:
  clusterIP: None
  selector:
    component: rtpengine
  ports:
    - name: metrics
      port: 22223
      protocol: TCP
