apiVersion: v1
kind: Secret
metadata:
  name: api-auth-secret
  namespace: voip
type: Opaque
stringData:
  authSecret: AUTH_SECRET

---

apiVersion: v1
kind: Secret
metadata:
  name: google-service-account
  namespace: voip
type: Opaque
stringData:
  key.json: |
    {
      "type":"service_account",
      "project_id":"PROJECT_ID",
      "private_key_id":"PKEYID",
      "private_key":"PRIVATEKEY",
      "client_email":"email@PROJECT_ID.iam.gserviceaccount.com",
      "client_id":"CLIENTID",
      "auth_uri":"https://accounts.google.com/o/oauth2/auth",
      "token_uri":"https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url":"https://www.googleapis.com/robot/v1/metadata/x509/email%40PROJECT_ID.iam.gserviceaccount.com"
    }

---

apiVersion: v1
kind: Secret
metadata:
  name: nats-url
  namespace: voip
type: Opaque
stringData:
  connectionString: nats://natsclient:PW@nats:4222
  user: natsclient
  pass: PW

---

apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: voip
stringData:
  .dockerconfigjson: |
    {
      "auths":{
        "ghcr.io":{
          "auth":"STRING"
        }
      }
    }
type: kubernetes.io/dockerconfigjson

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-url
  namespace: voip
type: Opaque
stringData:
  connectionString: mysql://main:main@mysql:3306/main

---

apiVersion: v1
kind: Secret
metadata:
  name: aws
  namespace: voip
type: Opaque
stringData:
  accessKey: KEY
  secretAccessKey: SECRET

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-pw
  namespace: voip
type: Opaque
stringData:
  pw: ROOTPW

---

apiVersion: v1
kind: Secret
metadata:
  name: apiban-key
  namespace: voip
type: Opaque
stringData:
  key: APIBANKEY

---

apiVersion: v1
kind: Secret
metadata:
  name: kamailio-dmq
  namespace: voip
type: Opaque
stringData:
  dns: _sip._udp.kamailio-dmq.example.com

